"""add avatar and disabled flag to users

Revision ID: ba7454288764
Revises: bc7270a45725
Create Date: 2026-10-03 23:43:44.542719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7454288764'
down_revision: Union[str, None] = 'bc7270a45725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_path', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_disabled')
    op.drop_column('users', 'avatar_path')
    # ### end Alembic commands ###
