"""add admin flag, last login and user settings

Revision ID: bc7270a45725
Revises: 7ffb6e64649e
Create Date: 2026-10-02 23:01:02.092095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7270a45725'
down_revision: Union[str, None] = '7ffb6e64649e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Bootstrap: with no admin yet, nobody could ever reach the admin panel
    # to create one. The oldest account (the person who set the app up) is
    # promoted. Does nothing on an empty database or if an admin exists.
    op.execute(
        """
        UPDATE users SET is_admin = true
        WHERE id = (SELECT id FROM users ORDER BY created_at ASC LIMIT 1)
          AND NOT EXISTS (SELECT 1 FROM users WHERE is_admin)
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_admin')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
